export { default as UButton } from '@/components/u-button/UButton.vue'
export { default as UIconButton } from '@/components/u-icon-button/UIconButton.vue'
export { default as UCheckbox } from '@/components/u-checkbox/Ucheckbox.vue'
export { default as URadio } from '@/components/u-radio/URadio.vue'
export { default as UToggle } from '@/components/u-toggle/UToggle.vue'
export { default as UDialog } from '@/components/u-dialog/UDialog.vue'
export { default as UAccordionPanel } from '@/components/u-accordion-panel/UAccordionPanel.vue'
export { default as UPagination } from '@/components/u-pagination/Upagination.vue'

export { default as theme } from '@/config/theme'
export { default as forms } from '@/plugin'
import 'virtual:windi.css'